name: AWSCodeBuild-Demo

on:
  workflow_dispatch:
env:
  SELF_HOSTED_RUNNER: codebuild-QualcommLinuxStg-MetaQcom-${{ github.run_id }}-${{ github.run_attempt }}
jobs:
  GH-To-AWS-CodeBuild-Integratio-Test:
    runs-on: 
      - codebuild-QualcommLinuxStg-MetaQcom-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3      
      - name: Build Code
        run: |
          id
          sudo -su builder; id ; echo $HOME
          mkdir /efs/${GITHUB_RUN_ID}
          echo "A Sample file for Artifactory Test for ${{ github.workflow }}" > /efs/${GITHUB_RUN_ID}/${{ github.workflow }}-${{ github.run_id}}.log
          find /efs/${GITHUB_RUN_ID}
          
      - name: GithubVariable
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
