name: AWSCodeBuild Demo
on:
  workflow_dispatch:
env:
  RUN_ATTEMPT: ${{ github.run_attempt }}
jobs:
  GH-To-AWS-CodeBuild-Integratio-Test:  
    runs-on:
      - codebuild-QualcommLinuxStg-MetaQcom-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
    env:
      JOB_RUNATTEMPT: SMDEBUG-${{ github.run_attempt }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3      
      - name: Build Code
        run: |
          id
          sudo -su builder; id ; echo $HOME
          
      - name: GithubVariable
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
