name: Build on push

on:
  push:
    branches:
      - main

jobs:
  build:
    #uses: ./.github/workflows/build-yocto.yml
    uses: ./.github/workflows/aws-build-yocto.yml
  test:
    uses: ./.github/workflows/test.yml
    needs: build
    secrets: inherit
    with:
      url: ${{ needs.build.outputs.artifacts_url }}
